### ISSUE TITLE
Highlighting occasionally persists beyond diagnostics or is applied incorrectly

### ISSUE THREAD

**Issue by akinsho** [zbirenbaum/neodim#5] opened 2022-06-16 19:36 UTC
Hi, 

Apologies in advance for spamming your repo with issues 😅 .
I've noticed over the course of the day I've been using this plugin that it occasionally doesn't clear the dimmed highlights, and rarely the highlights are applied incorrectly. The screenshot below shows a lua table where the highlighting is dimmed and a little garbled.

<img width="571" alt="image" src="https://user-images.githubusercontent.com/22454918/174150371-39757c25-2df9-4546-892b-449c7f3d016d.png">

Unfortunately I haven't discovered the pattern to trigger the garbling

**Comment by zbirenbaum** [comment] 2022-06-16 19:43
This is something I have witnessed too to some extent and I believe it is due to the caching system, although it also might be from the way extmarks work as well. At the time I wrote it I wasn't quite as knowledgeable and it's due for a cleanup. Originally this plugin was just for my personal use, and I just quickly go into insert mode and then escape to fix it. Since more people are coming to this repo now, its on my todo list.

It may fix itself if you enable update_in_insert, which will force refreshes that fix stuff like this, so you could try that if you aren't already in the meantime.

Never feel bad about posting issues! I'd rather have a backlog of things to fix than have dysfunctional plugins and not know it!

**Comment by zbirenbaum** [comment] 2022-06-17 01:26
Ok so I did a massive cleanup and rewrite, and since finishing it I haven't been able to reproduce this, so hopefully it is completely fixed. I'll reopen this issue if I manage to trigger it again though, please do the same if you happen to.

**Comment by zbirenbaum** [comment] 2022-06-17 23:11
I'm re-opening this because for some reason despite working perfectly while inside neodim's init.lua, it randomly makes mistakes in other files. I put out a quick fix that alleviates the worst behavior, but it still needs improving.

**Comment by zbirenbaum** [comment] 2022-06-20 06:43
Ok I think I finally have this fixed. I can't reproduce it, and even if it was was somehow triggered by some edge case, the new `update_in_insert` option would definitely fix it if its on.

Try out the new feature (it's the new default but make sure your diagnostic.config has update_in_insert set to false) and let me know how it goes. 

I'll just let you close this if you feel it's not an issue anymore since last time I thought I fixed it I ended up being entirely wrong.

**Comment by akinsho** [comment] 2022-06-20 06:53
Awesome, sounds great I'll test it over the course of the day and close this if I don't see anything 👍🏿

**Comment by zbirenbaum** [comment] 2022-06-22 17:35
> Awesome, sounds great I'll test it over the course of the day and close this if I don't see anything 👍🏿 

Did you happen to notice anything? Just trying to clean up my open issues so I can make a todo list.

**Comment by akinsho** [comment] 2022-06-22 20:37
Nope no sign of any issues

**Closed as completed** 2022-06-22 20:38 UTC
